---
name: Test
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.2'
          - '2.3'
          - '2.4'
          - jruby-9.1.17.0
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: sudo apt-get install -y ragel

      - run: bundle exec rake
